# Generated by Django 3.1.3 on 2020-12-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20201212_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='latitude',
            new_name='bedroom',
        ),
    ]
